# Utilisez une image PHP avec Apache
FROM php:8.1-apache

# Installation des dépendances nécessaires
RUN apt-get update && \
    apt-get install -y \
    libicu-dev \
    libzip-dev \
    unzip \
    git

# Installation des extensions PHP nécessaires
RUN docker-php-ext-install \
    pdo_mysql \
    intl \
    zip

# Configuration d'Apache pour Symfony
RUN a2enmod rewrite
COPY apache-config.conf /etc/apache2/sites-available/000-default.conf

# Installation de Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Création du répertoire de l'application Symfony
WORKDIR /var/www/html

# Copie des fichiers de l'application
COPY . .

# Installation des dépendances Symfony
RUN composer install --no-scripts --no-autoloader

# Chargement de l'autoload et exécution des scripts Symfony
RUN composer dump-autoload --optimize && \
    composer run-script post-install-cmd

# Exposition du port 80
EXPOSE 80

# Commande par défaut pour exécuter Apache
CMD ["apache2-foreground"]
