# Use an official PHP runtime as a parent image
FROM php:8.1-apache

# Set the working directory to /var/www/html
WORKDIR /var/www/html

ENV APP_ENV=dev

RUN a2enmod rewrite
COPY docker/apache/vhost.conf /etc/apache2/sites-available/000-default.conf

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    unzip

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql

# Enable Apache modules
RUN a2enmod rewrite

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy composer.json and composer.lock to the container
COPY composer.json composer.lock ./

# Install Symfony dependencies
RUN composer install --no-scripts --no-autoloader

# Copy the application code to the container
COPY . .

# Generate the Symfony autoloader
RUN composer dump-autoload --no-scripts --optimize

# Create the Symfony var directory
RUN mkdir -p var
# Set proper permissions for the Symfony var directory
RUN chown -R www-data:www-data var

# Expose port 80 for the Apache server
EXPOSE 80

# Define the command to run the application
CMD ["apache2-foreground"]
